
data:
  raw_dir: "data/"
  # raw_dir: "../audioDemo/data/raw"
  sample_rate: 16000
  batch_size: 256
  version: "v0.1"

model_type: "wav2vec2"

model:
  wav2vec2:

train:
  learning_rate: 0.00005
  per_device_train_batch_size: 32
  gradient_accumulation_steps: 4
  per_device_eval_batch_size: 32
  num_train_epochs: 10
  warmup_ratio: 0.1
  logging_steps: 50

  version: "demo"